### ISSUE TITLE
HMR can result in DOM duplicates when importing nested modules from main.js

### ISSUE THREAD

**Issue by jsprog** [rixo/rollup-plugin-hot#4]
This bug is confirmed with both: **svelte-template-hot** and **svelte-template-hot@next**. Not appearing in **_svelte-template-webpack-hot_** due to **auto reload** when updating the nested imports used by **main.js**

**To recreate this bug:**

- import a module (e.g: **db.js**) that import 2 other modules (e.g: **Database.js** and **UserAccount.js**) those import the same third module (e.g: **codec.js**)
- save **codec.js** to trigger HMR

**Notes:**
- This bug behaves differently when importing from './db/db' instead of './db'. In the case provided by the example ('./db'), you won't see any duplicate until you save codec.js a second time to see 2 duplicates.
  - when importing from './db/db', this bug will kicks only after saving codec.js, and only one extra DOM duplicate per save. subsequent saves to other files depending on codec.js won't push extra duplicates.
  - when importing from either './db' or './db/index', 2 extra DOM duplicates appear per every save for codec.js starting from the second save. subsequent saves to other files depending on codec.js push just one extra duplicate.
- This bug won't appear when importing from App.svelte instead.
- This bug won't appear when importing both **Database.js** and **UserAccount.js** directly instead of './db/index' or './db/db' instead.
- This bug may get triggered unpredictably depending on the nested imports and the change triggering the HMR. In fact, Better be resolved or at least force a full reload (auto reload) when one of the dependencies of main.js change (of course App.svelte change shouldn't trigger a full reload).

**Example code:**
```javascript
// App.svelte
// onMount and onDestroy for logging

// main.js
import db from './db'
// ... keep template code

// db/index.js
import db from './db'
export default db

// db/db.js
import Database from './Database'
import UserAccount from './UserAccount'
const db = new Database()
export default db

// db/Database.js
import codec from './codec'
export default class Database {}

// db/UserAccount.js
import codec from './codec'
export default class UserAccount {}

// db/codec.js
export default {
    encode () {},
    decode () {}
}
```

**Comment by rixo** [comment]
I'm moving this issue to `rollup-plugin-hot` were the bug really originates (don't worry too much about finding the right project for reporting, it's often hard to tell -- svelte-hmr for everything is fine, I'm happy to do triage ; anyway, thanks again for taking the time to give detailed feedback).

**Comment by jsprog** [comment]
Note sure when this issue got solved, but I could confirm that I'm not facing the same issue after testing again with the last version of **svelte-template-hot**
