### ISSUE TITLE
input values state on hmr

### ISSUE THREAD

**Issue by aelbore** [rixo/rollup-plugin-hot#8]
when any component change does the state still maintain? 
for example i have input element and has a value when hmr trigger does the value of input will not empty or disappear?

**Comment by rixo** [comment]
This plugin works entirely at the module (i.e. js file) level. It notifies the browser of modules that change, and reloads them. It doesn't play a role in how replacing a JS file affects the DOM. This is done by your own accept handlers, or the HMR adapters you're using...

Is your question specific to the Svelte plugin?

**Comment by aelbore** [comment]
@rixo its for vanilla javascript, im thinking same of react hot reload, when page reload it remains or maintain the states. do you have any example on how to create just simple accept handlers or HMR adapters? thanks

**Comment by rixo** [comment]
Oh cool, this is taking a life of its own :) I guess this plugin has ever been used for Svelte HMR, before your experiments... I'm quite curious about what you're working on.

Also, I'm very open to implement features to support your use cases if needed. For now it has more or less be tailored around supporting Svelte HMR, but it would be cool if it could support more general HMR use cases. So feel free to open issues to discuss what you need!

I have [documented the hot API](https://github.com/rixo/rollup-plugin-hot#api) and written an [advanced example / mini tutorial](https://github.com/rixo/rollup-plugin-hot/tree/master/example/src/stateful) on how to implement a HMR adapter (at least, that's how I learnt to do it). I have written that in a hurry, and the subject is very dense, so I hope you'll manage to make sense of it... I think this thread is a good place if you have any follow up question, so I'll leave the issue open for now.

**Comment by aelbore** [comment]
@rixo thanks i take a look of the example, actually been currently working on a tools than can serve/build/test any javascript underhood im using rollup one of your plugin im been using it.
i inspired with vite by vuejs 
this is my repo: https://github.com/aelbore/aria-serve

**Comment by rixo** [comment]
Closing this. Feel free to reach again if you have some more questions. Good luck with your project!
